### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by apmccartney**

### CODE REVIEW

**Comment by apmccartney** [comment]
Note the failing test is related to the webpage build. It's suspect it's related to the fact that travis is building the fork rather than the host repository page.

**Comment by fosterbrereton** [comment]
What's happened is Adobe has rerouted `stlab.adobe.com/wiki` -> `stlab.cc`. I'm not sure when they did this, but it was after 1.0 and before today. Anyhow, those links don't exist on stlab.cc, so they're 404-ing, which is a build error. Since we only build the docs on an as-needed basis, whereas they worked for 1.0 they're busted now. I'll clean them up, then review the PR and get it merged into develop- hopefully sometime later tonight. So far, though, this is all great stuff!

**Comment by fosterbrereton** [comment]
@apmccartney I fixed the broken links in `develop` - can you merge the changes into your PR?

**Comment by apmccartney** [comment]
Good find. Changes merged and tests passed.

**Comment by fosterbrereton** [comment]
Solid work, thanks again

**Pull request merged**
